version: '3.8'

services:
  grpc-server:
    build: ./
    ports:
      - 50051:50051
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - ./db-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
