// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: api/server.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalcServer_Add_FullMethodName  = "/grpc_course.CalcServer/Add"
	CalcServer_Add2_FullMethodName = "/grpc_course.CalcServer/Add2"
)

// CalcServerClient is the client API for CalcServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalcServerClient interface {
	Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddRsp, error)
	Add2(ctx context.Context, in *AddReq2, opts ...grpc.CallOption) (*AddRsp, error)
}

type calcServerClient struct {
	cc grpc.ClientConnInterface
}

func NewCalcServerClient(cc grpc.ClientConnInterface) CalcServerClient {
	return &calcServerClient{cc}
}

func (c *calcServerClient) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRsp)
	err := c.cc.Invoke(ctx, CalcServer_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcServerClient) Add2(ctx context.Context, in *AddReq2, opts ...grpc.CallOption) (*AddRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRsp)
	err := c.cc.Invoke(ctx, CalcServer_Add2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalcServerServer is the server API for CalcServer service.
// All implementations must embed UnimplementedCalcServerServer
// for forward compatibility.
type CalcServerServer interface {
	Add(context.Context, *AddReq) (*AddRsp, error)
	Add2(context.Context, *AddReq2) (*AddRsp, error)
	mustEmbedUnimplementedCalcServerServer()
}

// UnimplementedCalcServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalcServerServer struct{}

func (UnimplementedCalcServerServer) Add(context.Context, *AddReq) (*AddRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedCalcServerServer) Add2(context.Context, *AddReq2) (*AddRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add2 not implemented")
}
func (UnimplementedCalcServerServer) mustEmbedUnimplementedCalcServerServer() {}
func (UnimplementedCalcServerServer) testEmbeddedByValue()                    {}

// UnsafeCalcServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalcServerServer will
// result in compilation errors.
type UnsafeCalcServerServer interface {
	mustEmbedUnimplementedCalcServerServer()
}

func RegisterCalcServerServer(s grpc.ServiceRegistrar, srv CalcServerServer) {
	// If the following call pancis, it indicates UnimplementedCalcServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalcServer_ServiceDesc, srv)
}

func _CalcServer_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServerServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalcServer_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServerServer).Add(ctx, req.(*AddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalcServer_Add2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReq2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServerServer).Add2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalcServer_Add2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServerServer).Add2(ctx, req.(*AddReq2))
	}
	return interceptor(ctx, in, info, handler)
}

// CalcServer_ServiceDesc is the grpc.ServiceDesc for CalcServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalcServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_course.CalcServer",
	HandlerType: (*CalcServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _CalcServer_Add_Handler,
		},
		{
			MethodName: "Add2",
			Handler:    _CalcServer_Add2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/server.proto",
}
