// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: api/server.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Temp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Temp) Reset() {
	*x = Temp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Temp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temp) ProtoMessage() {}

func (x *Temp) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temp.ProtoReflect.Descriptor instead.
func (*Temp) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{0}
}

func (x *Temp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type AddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A    int32 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B    int32 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	Temp *Temp `protobuf:"bytes,3,opt,name=temp,proto3" json:"temp,omitempty"`
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{1}
}

func (x *AddReq) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddReq) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *AddReq) GetTemp() *Temp {
	if x != nil {
		return x.Temp
	}
	return nil
}

type AddReq2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []int32 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *AddReq2) Reset() {
	*x = AddReq2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReq2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq2) ProtoMessage() {}

func (x *AddReq2) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq2.ProtoReflect.Descriptor instead.
func (*AddReq2) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{2}
}

func (x *AddReq2) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type AddRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddRsp) Reset() {
	*x = AddRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRsp) ProtoMessage() {}

func (x *AddRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRsp.ProtoReflect.Descriptor instead.
func (*AddRsp) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{3}
}

func (x *AddRsp) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_api_server_proto protoreflect.FileDescriptor

var file_api_server_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a,
	0x04, 0x54, 0x65, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a, 0x06, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x62, 0x12,
	0x25, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x54, 0x65, 0x6d, 0x70,
	0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x22, 0x21, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71,
	0x32, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x20, 0x0a, 0x06, 0x41, 0x64, 0x64,
	0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x96, 0x01, 0x0a, 0x0a,
	0x43, 0x61, 0x6c, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x03, 0x41, 0x64,
	0x64, 0x12, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x73, 0x70, 0x22, 0x12, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0c, 0x3a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x22, 0x04, 0x2f, 0x61, 0x64, 0x64, 0x12,
	0x43, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x32, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x32, 0x1a, 0x13, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x52,
	0x73, 0x70, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x3a, 0x01, 0x2a, 0x22, 0x05, 0x2f,
	0x61, 0x64, 0x64, 0x32, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6b, 0x68, 0x6f, 0x76, 0x61, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_server_proto_rawDescOnce sync.Once
	file_api_server_proto_rawDescData = file_api_server_proto_rawDesc
)

func file_api_server_proto_rawDescGZIP() []byte {
	file_api_server_proto_rawDescOnce.Do(func() {
		file_api_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_server_proto_rawDescData)
	})
	return file_api_server_proto_rawDescData
}

var file_api_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_server_proto_goTypes = []any{
	(*Temp)(nil),    // 0: grpc_course.Temp
	(*AddReq)(nil),  // 1: grpc_course.AddReq
	(*AddReq2)(nil), // 2: grpc_course.AddReq2
	(*AddRsp)(nil),  // 3: grpc_course.AddRsp
}
var file_api_server_proto_depIdxs = []int32{
	0, // 0: grpc_course.AddReq.temp:type_name -> grpc_course.Temp
	1, // 1: grpc_course.CalcServer.Add:input_type -> grpc_course.AddReq
	2, // 2: grpc_course.CalcServer.Add2:input_type -> grpc_course.AddReq2
	3, // 3: grpc_course.CalcServer.Add:output_type -> grpc_course.AddRsp
	3, // 4: grpc_course.CalcServer.Add2:output_type -> grpc_course.AddRsp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_server_proto_init() }
func file_api_server_proto_init() {
	if File_api_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Temp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddReq2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AddRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_server_proto_goTypes,
		DependencyIndexes: file_api_server_proto_depIdxs,
		MessageInfos:      file_api_server_proto_msgTypes,
	}.Build()
	File_api_server_proto = out.File
	file_api_server_proto_rawDesc = nil
	file_api_server_proto_goTypes = nil
	file_api_server_proto_depIdxs = nil
}
